### ISSUE TITLE
I can't launch cameracalibrator.launch 

### ISSUE THREAD

**Issue by caemoon2** [ethz-asl/ethzasl_ptam#73]
Hello, I'm trying to launch ptam calibrator with following some tutorial.
But when I use following command, 

roslaunch ptam cameracalibrator.launch

I got the next result,
[cameracalibrator.launch] is neither a launch file in package [ptam] nor is [ptam] a launch file name
The traceback for the exception was written to the log file

I'm really new to ROS and computer vision so I have no idea what is wrong with my computer...

http://www.hyperbolicthoughts.co.uk/2015/05/lsd-slam-install.html
this is a link for the tutorial, I was following, and under the calibrate camera part, you can see the line of command and others.
I think the setup of ptam was successful, because I can see the launch file under devel folder, which is under my catkin folder. So anybody can give me some advice for my issue?

Thanks in advance,

**Comment by ssampang** [comment]
You need to run `source CATKIN_DIR/devel/setup.bash` where CATKIN_DIR is the location of your base catkin workspace folder.

**Comment by caemoon2** [comment]
@ssampang  Thanks Ssampang, I moved one step further. However, I got different and long error, which  I can't totally understand and I have no idea how to solve the error,

moon@Mubuntu:~/catkin_ws$ source devel/setup.bash 
moon@Mubuntu:~/catkin_ws$ roslaunch ptam cameracalibrator.launch
... logging to /home/moon/.ros/log/e1f94022-36e5-11e5-bc26-e0915376966c/roslaunch-Mubuntu-23365.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Mubuntu:56341/

# SUMMARY

CLEAR PARAMETERS
- /cameracalibrator/

PARAMETERS
- /cameracalibrator/ARBuffer_height: 900
- /cameracalibrator/ARBuffer_width: 1200
- /cameracalibrator/AutoInitPixel: 20
- /cameracalibrator/BundleMEstimator: Tukey
- /cameracalibrator/Calibrator_BlurSigma: 1.0
- /cameracalibrator/Calibrator_MeanGate: 10
- /cameracalibrator/Calibrator_MinCornersForGrabbedImage: 20
- /cameracalibrator/Calibrator_NoDistortion: 0
- /cameracalibrator/Calibrator_Optimize: 0
- /cameracalibrator/Calibrator_Show: 0
- /cameracalibrator/Cam_cx: 0.50417
- /cameracalibrator/Cam_cy: 0.51687
- /cameracalibrator/Cam_fx: 0.795574
- /cameracalibrator/Cam_fy: 1.25149
- /cameracalibrator/Cam_s: 0.482014
- /cameracalibrator/CameraCalibrator_CornerPatchSize: 20
- /cameracalibrator/CameraCalibrator_MaxStepDistFraction: 0.3
- /cameracalibrator/CandidateMinSTScore: 70
- /cameracalibrator/FASTMethod: OAST16
- /cameracalibrator/GLWindowMenu_Enable: True
- /cameracalibrator/GLWindowMenu_mgvnMenuItemWidth: 90
- /cameracalibrator/GLWindowMenu_mgvnMenuTextOffset: 20
- /cameracalibrator/ImageSizeX: 640
- /cameracalibrator/ImageSizeY: 480
- /cameracalibrator/InitLevel: 1
- /cameracalibrator/MaxKF: 15
- /cameracalibrator/MaxKFDistWiggleMult: 1
- /cameracalibrator/MaxPatchesPerFrame: 300
- /cameracalibrator/MaxStereoInitLoops: 4
- /cameracalibrator/MinTukeySigma: 0.4
- /cameracalibrator/NoLevelZeroMapPoints: True
- /cameracalibrator/TrackerMEstimator: Tukey
- /cameracalibrator/TrackingQualityFoundPixels: 50
- /cameracalibrator/UseKFPixelDist: True
- /cameracalibrator/WiggleScale: 0.1
- /cameracalibrator/gui: True
- /cameracalibrator/parent_frame: world
- /rosdistro: indigo
- /rosversion: 1.11.13

NODES
  /
    cameracalibrator (ptam/cameracalibrator)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[cameracalibrator-1]: started with pid [23384]
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
---Type <return> to continue, or q <return> to quit---return
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/moon/catkin_ws/devel/lib/ptam/cameracalibrator...(no debugging symbols found)...done.
Starting program: /home/moon/catkin_ws/devel/lib/ptam/cameracalibrator image:=bluefox_ros_node/image_raw pose:=pose __name:=cameracalibrator __log:=/home/moon/.ros/log/e1f94022-36e5-11e5-bc26-e0915376966c/cameracalibrator-1.log
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[New Thread 0x7fffea1d9700 (LWP 23588)]
[New Thread 0x7fffe99d8700 (LWP 23589)]
[New Thread 0x7fffe71d7700 (LWP 23590)]
[ INFO] [1438285499.480204674]: starting CameraCalibrator with node name /cameracalibrator
  Welcome to CameraCalibrator 

---

  Parallel tracking and mapping for Small AR workspaces
  Copyright (C) Isis Innovation Limited 2008 
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[New Thread 0x7fffe20e8700 (LWP 23592)]
[New Thread 0x7fffe18e7700 (LWP 23593)]
[New Thread 0x7fffe10e6700 (LWP 23594)]
[New Thread 0x7fffe08e5700 (LWP 23599)]
Gui is on
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[Thread 0x7fffea1d9700 (LWP 23588) exited]
[Thread 0x7fffe71d7700 (LWP 23590) exited]
[Thread 0x7fffe99d8700 (LWP 23589) exited]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
[tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]

and when I interrupt this process by ctrl+c,
I got following messages

^C[cameracalibrator-1] killing on exit
[cameracalibrator-1] escalating to SIGTERM
Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1279, in _shutdown
    def _shutdown():
KeyboardInterrupt
shutting down processing monitor...
... shutting down processing monitor complete
done

Can anybody get some idea about this error? I don't even know what is ioctl.....

**Comment by caemoon2** [comment]
Another case,
when I tried to launch the cameracalibrator with original launch file, which includes original contents,
- launch>
-    node name="cameracalibrator" pkg="ptam" type="cameracalibrator" clear_params="true" --output="screen">
-       remap from="image" to="bluefox_ros_node/image_raw" />
-          remap from="pose" to="pose"/>
-       rosparam file="$(find ptam)/PtamFixParams.yaml"/>
-    /node>
- /launch>

Then I launched 
~/catkin_ws$ roslaunch ptam cameracalibrator.launch

the result is
... logging to /home/moon/.ros/log/23d8f6ea-36fa-11e5-81bc-e0915376966c/roslaunch-Mubuntu-4813.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Mubuntu:47490/

# SUMMARY

CLEAR PARAMETERS
- /cameracalibrator/

PARAMETERS
- /cameracalibrator/ARBuffer_height: 900
- /cameracalibrator/ARBuffer_width: 1200
- /cameracalibrator/AutoInitPixel: 20
- /cameracalibrator/BundleMEstimator: Tukey
- /cameracalibrator/Calibrator_BlurSigma: 1.0
- /cameracalibrator/Calibrator_MeanGate: 10
- /cameracalibrator/Calibrator_MinCornersForGrabbedImage: 20
- /cameracalibrator/Calibrator_NoDistortion: 0
- /cameracalibrator/Calibrator_Optimize: 0
- /cameracalibrator/Calibrator_Show: 0
- /cameracalibrator/Cam_cx: 0.50417
- /cameracalibrator/Cam_cy: 0.51687
- /cameracalibrator/Cam_fx: 0.795574
- /cameracalibrator/Cam_fy: 1.25149
- /cameracalibrator/Cam_s: 0.482014
- /cameracalibrator/CameraCalibrator_CornerPatchSize: 20
- /cameracalibrator/CameraCalibrator_MaxStepDistFraction: 0.3
- /cameracalibrator/CandidateMinSTScore: 70
- /cameracalibrator/FASTMethod: OAST16
- /cameracalibrator/GLWindowMenu_Enable: True
- /cameracalibrator/GLWindowMenu_mgvnMenuItemWidth: 90
- /cameracalibrator/GLWindowMenu_mgvnMenuTextOffset: 20
- /cameracalibrator/ImageSizeX: 640
- /cameracalibrator/ImageSizeY: 480
- /cameracalibrator/InitLevel: 1
- /cameracalibrator/MaxKF: 15
- /cameracalibrator/MaxKFDistWiggleMult: 1
- /cameracalibrator/MaxPatchesPerFrame: 300
- /cameracalibrator/MaxStereoInitLoops: 4
- /cameracalibrator/MinTukeySigma: 0.4
- /cameracalibrator/NoLevelZeroMapPoints: True
- /cameracalibrator/TrackerMEstimator: Tukey
- /cameracalibrator/TrackingQualityFoundPixels: 50
- /cameracalibrator/UseKFPixelDist: True
- /cameracalibrator/WiggleScale: 0.1
- /cameracalibrator/gui: True
- /cameracalibrator/parent_frame: world
- /rosdistro: indigo
- /rosversion: 1.11.13

NODES
  /
    cameracalibrator (ptam/cameracalibrator)

auto-starting new master
process[master]: started with pid [4825]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 23d8f6ea-36fa-11e5-81bc-e0915376966c
process[rosout-1]: started with pid [4838]
started core service [/rosout]
process[cameracalibrator-2]: started with pid [4856]
[ INFO] [1438288368.319376314]: starting CameraCalibrator with node name /cameracalibrator
  Welcome to CameraCalibrator 

---

  Parallel tracking and mapping for Small AR workspaces
  Copyright (C) Isis Innovation Limited 2008 
Gui is on

But I didn't see an GUI,,,, where is the guy??? 

I can't find any solution,, even I spend most of my time today....

thank you in advance...

**Comment by ssampang** [comment]
Are you intending to use a webcam with ptam? It might be helpful to get a brief understanding of how ROS image topics work. They follow a publisher/subscriber model where something needs to register as a "topic" with ROS and publish images/frames under its name, which ptam will then subscribe to. That is the role of the line `remap from="image" to="bluefox_ros_node/image_raw" />` in both of the .launch files. It tells ptam the name of the image topic it needs to subscribe to. I'm not 100% sure how this works with webcams as I've personally been using saved images, but you'll need to change the `"image"` to the name of the topic that your webcam publishes under. Hope that helps.
